---
- name: install utilities
  pacman:
    name:
      - aria2
      - bcc-tools
      - bind-tools
      - curl
      - gvfs
      - htop
      - httpie
      - iotop
      - iw
      - jq
      - less
      - nmap
      - openssh
      - python-bcc
      - ripgrep
      - rsync
      - shellcheck
      - strace
      - sysstat
      - udisks2
      - unzip
      - usbutils
      - which
  become: true

- name: install applications
  pacman:
    name:
      - firefox
      - hunspell-en_US # Firefox spellcheck
      - evince
      - mpv
      - pcmanfm-gtk3
      - viewnior
  become: true
