---
- name: install audio tools
  pacman:
    name:
      - pipewire
      - pipewire-docs
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - pipewire-audio
      - alsa-utils
      - pavucontrol
  become: true

- name: configure x11 key bindings
  copy:
    src: xbindkeysrc
    dest: /home/{{ archlinux_username }}/.xbindkeysrc
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0644
  become: true
  become_user: "{{ archlinux_username }}"
