---
- name: Install audio tools
  community.general.pacman:
    name:
      - pipewire
      - pipewire-docs
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - pipewire-audio
      - alsa-utils
      - pavucontrol
  become: true

- name: Configure x11 key bindings
  ansible.builtin.copy:
    src: xbindkeysrc
    dest: /home/{{ archlinux_username }}/.xbindkeysrc
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0644"
  become: true
  become_user: "{{ archlinux_username }}"
