---
- name: install firmware
  pacman:
    name: linux-firmware
  become: true

- name: install intel microcode
  pacman:
    name: intel-ucode
  when: "'GenuineIntel' in ansible_processor"
  become: true

- name: install amd microcode
  pacman:
    name: amd-ucode
  when: "'AuthenticAMD' in ansible_processor"
  become: true

- name: install networking tools
  pacman:
    name:
      - netctl
      - openvpn
      - wpa_supplicant
  become: true

- name: install filesystem tools
  pacman:
    name:
      - cryptsetup
      - e2fsprogs
  become: true

- name: install audio tools
  pacman:
    name:
      - alsa-firmware
      - alsa-utils
      - paprefs
      - pavucontrol
      - pulseaudio
      - pulseaudio-alsa
  become: true

- name: install man pages
  pacman:
    name:
      - man-db
      - man-pages

- name: install utilities
  pacman:
    name:
      - aria2
      - curl
      - htop
      - httpie
      - iotop
      - jq
      - less
      - nmap
      - openssh
      - ripgrep
      - rsync
      - shellcheck
      - usbutils
      - which
  become: true

- name: uninstall ntpd
  pacman:
    name: ntp
    state: absent
  become: true

- name: enable network time
  service:
    name: systemd-timesyncd
    state: started
    enabled: true
  become: true

- name: enable firewall
  service:
    name: iptables
    state: started
    enabled: true
  become: true

- name: install shell colorschemes
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: /home/{{ archlinux_username }}/.config/base16-shell
    version: master
  become: true
  become_user: "{{ archlinux_username }}"

- name: install fonts
  pacman:
    name:
      - adobe-source-code-pro-fonts
      - powerline-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-inconsolata
      - ttf-liberation
  become: true

- name: install GUI
  pacman:
    name:
      - arandr
      - elementary-icon-theme
      - lightdm
      - lightdm-gtk-greeter
      - lxappearance
      - xcursor-simpleandsoft
  become: true

- name: enable GUI on boot
  service:
    name: lightdm
    enabled: true
  become: true

- name: template .bashrc
  copy:
    src: bashrc
    dest: /home/{{ archlinux_username}}/.bashrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: template Xresources
  template:
    src: Xresources
    dest: /home/{{ archlinux_username }}/.Xresources
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: install applications
  pacman:
    name:
      - chromium
      - evince
      - firefox
      - kitty
      - mpv
      - pcmanfm
      - viewnior
  become: true

- name: create AUR build directory
  file:
    name: /home/{{ archlinux_username }}/build
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: create scripts directory
  file:
    name: /home/{{ archlinux_username }}/bin
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: configure direnv (must be installed separately via AUR or Go)
  copy:
    src: direnvrc
    dest: /home/{{ archlinux_username }}/.direnvrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

- name: create kitty configuration directory
  file:
    dest: /home/{{ archlinux_username }}/.config/kitty
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
  become: true

- name: configure kitty
  template:
    src: kitty.conf
    dest: /home/{{ archlinux_username }}/.config/kitty/kitty.conf
    owner: "{{ archlinux_username }}"
    group: users
  become: true
