---
- name: install firmware
  pacman:
    name: linux-firmware
  become: true

- name: install filesystem tools
  pacman:
    name:
      - cryptsetup
      - e2fsprogs
  become: true

- name: install man pages
  pacman:
    name:
      - man-db
      - man-pages

- name: install utilities
  pacman:
    name:
      - aria2
      - curl
      - htop
      - httpie
      - iotop
      - jq
      - less
      - nmap
      - openssh
      - ripgrep
      - rsync
      - shellcheck
      - usbutils
      - which
  become: true

- name: install fonts
  pacman:
    name:
      - adobe-source-code-pro-fonts
      - powerline-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-inconsolata
      - ttf-liberation
  become: true

- name: install GUI
  pacman:
    name:
      - arandr
      - elementary-icon-theme
      - lightdm
      - lightdm-gtk-greeter
      - lxappearance
      - xcursor-simpleandsoft
  become: true

- name: enable GUI on boot
  service:
    name: lightdm
    enabled: true
  become: true

- name: install applications
  pacman:
    name:
      - chromium
      - evince
      - firefox
      - mpv
      - pcmanfm
      - viewnior
  become: true
