---
- name: detect display controllers
  # PCI ID 03XX = Display Controller
  # There are four subcategories of display controller, and a graphics chip may
  # report as any of them
  shell: lspci -mnn | grep -E '\[03[0-9]{2}]' | grep -i {{ item }}  # noqa no-changed-when
  with_items:
    - amd
    - intel
    - nvidia
  register: display_controllers
  ignore_errors: true  # noqa ignore-errors

- name: install mesa (OpenGL implementation)
  pacman:
    name:
      - mesa
      - libva-mesa-driver  # Video decoding acceleration (VA-API)
      - mesa-vdpau  # Video decoding acceleration (VDPAU)
  become: true

- name: install AMD display drivers
  pacman:
    name:
      - xf86-video-amdgpu
      - vulkan-radeon  # Vulkan
  when: not display_controllers.results[0].failed
  become: true

- name: install Intel display drivers
  pacman:
    name:
      - xf86-video-intel
      # VA-API support varies by generation, so we'll install all of the
      # applicable packages and hope one works
      - intel-media-driver
      - libva-intel-driver
      # Intel doesn't support VDPAU natively, so install a VDPAU to VA-API
      # translation layer
      - libvdpau-va-gl
  when: not display_controllers.results[1].failed
  become: true

- name: install Nvidia display drivers
  pacman:
    name:
      - nvidia
  when: not display_controllers.results[2].failed
  become: true
