---
- name: Install xinit
  community.general.pacman:
    name:
      - xorg-xinit
  become: true

- name: Install fonts
  community.general.pacman:
    name:
      - adobe-source-code-pro-fonts
      - adobe-source-han-sans-jp-fonts
      - noto-fonts
      - noto-fonts-emoji
      - powerline-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-inconsolata
      - ttf-liberation
  become: true

- name: Install display configuration tools
  community.general.pacman:
    name:
      - arandr
      - lxrandr
  become: true

- name: Install xclip
  community.general.pacman:
    name:
      - xclip
  become: true

- name: Install GUI themes
  community.general.pacman:
    name:
      - elementary-icon-theme
      - gnome-themes-extra
      - lxappearance-gtk3
  become: true
