---
- name: Install kitty
  community.general.pacman:
    name: kitty
  become: true

- name: Create kitty configuration directory
  ansible.builtin.file:
    dest: /home/{{ archlinux_username }}/.config/kitty
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0755"
  become: true

- name: Configure kitty
  ansible.builtin.template:
    src: kitty.conf
    dest: /home/{{ archlinux_username }}/.config/kitty/kitty.conf
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0644"
  become: true
