---
- name: install libvirt and QEMU
  pacman:
    name:
      - dmidecode
      - dnsmasq
      - ebtables
      - libvirt
      - qemu
      - virt-manager
  become: true

- name: enable libvirtd
  systemd:
    name: libvirt.service
    state: started
    enabled: true
  become: true
