---
- name: install networking tools
  pacman:
    name:
      - netctl
      - openvpn
      - wpa_supplicant
  become: true

- name: enable firewall
  systemd:
    name: iptables
    state: started
    enabled: true
  become: true
