---
- name: Start openssh server
  systemd:
    name: sshd
    state: started
  when: archlinux_enable_openssh_server
  become: true

- name: Configure openssh server
  ansible.builtin.copy:
    src: openssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: sshd -t -f %s
  become: true
  notify:
    - restart openssh server

- name: Disable weak openssh moduli
  ansible.builtin.script:
    cmd: openssh/disable_weak_moduli.sh
  become: true
  notify:
    - restart openssh server

- name: Enable openssh server
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: true
  when: archlinux_enable_openssh_server
  become: true

- name: Disable openssh server
  ansible.builtin.systemd:
    name: sshd
    state: stopped
    enabled: false
  when: not archlinux_enable_openssh_server
  become: true
