---
- name: Install sway
  community.general.pacman:
    name:
      - sway
      - polkit
      - swaylock
      - swaybg
      - wmenu
      - cliphist
      - xorg-xwayland
  become: true

- name: Create swat configuration directory
  ansible.builtin.file:
    name: /home/{{ archlinux_username }}/.config/sway
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0755"
  become: true

- name: Configure sway
  ansible.builtin.template:
    src: sway/config
    dest: /home/{{ archlinux_username }}/.config/sway/config
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0644"
  become: true
