---
- name: Uninstall ntpd
  community.general.pacman:
    name: ntp
    state: absent
  become: true

- name: Enable network time
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: started
    enabled: true
  become: true
