---
- name: create normal user
  user:
    name: "{{ archlinux_username }}"
    create_home: true
    group: users
    groups:
      - wheel
  become: true

- name: create scripts directory
  file:
    name: /home/{{ archlinux_username }}/bin
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0755
  become: true
  become_user: "{{ archlinux_username }}"

- name: copy dotfiles
  copy:
    src: "{{ item }}"
    dest: /home/{{ archlinux_username }}/.{{ item }}
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0600
  with_items:
    - bashrc
    - bash_profile
    - xinitrc
    - direnvrc
  become: true
  become_user: "{{ archlinux_username }}"

- name: template dotfiles
  template:
    src: "{{ item }}"
    dest: /home/{{ archlinux_username }}/.{{ item }}
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0600
  with_items:
    - Xresources
  become: true
  become_user: "{{ archlinux_username }}"

- name: create openssh client configuration directory
  file:
    dest: /home/{{ archlinux_username }}/.ssh
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0700
  become: true

- name: configure openssh client
  copy:
    src: openssh/ssh_config
    dest: /home/{{ archlinux_username }}/.ssh/config
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0644
  become: true
  become_user: "{{ archlinux_username }}"

- name: install shell colorschemes
  git:
    repo: "https://github.com/dharmab/base16-shell.git"
    dest: /home/{{ archlinux_username }}/.config/base16-shell
    version: master
  become: true
  become_user: "{{ archlinux_username }}"
