---
- name: create normal user
  user:
    name: "{{ archlinux_username }}"
    create_home: true
    group: users
    groups:
      - wheel
      - docker
  become: true

- name: create scripts directory
  file:
    name: /home/{{ archlinux_username }}/bin
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

- name: template .bashrc
  copy:
    src: bashrc
    dest: /home/{{ archlinux_username}}/.bashrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

- name: install shell colorschemes
  git:
    repo: "https://github.com/dharmab/base16-shell.git"
    dest: /home/{{ archlinux_username }}/.config/base16-shell
    version: master
  become: true
  become_user: "{{ archlinux_username }}"

- name: configure direnv (must be installed separately via AUR or Go)
  copy:
    src: direnvrc
    dest: /home/{{ archlinux_username }}/.direnvrc
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

- name: configure Xresources
  template:
    src: Xresources
    dest: /home/{{ archlinux_username }}/.Xresources
    owner: "{{ archlinux_username }}"
    group: users
  become: true
  become_user: "{{ archlinux_username }}"

