---
- name: Create normal user
  ansible.builtin.user:
    name: "{{ archlinux_username }}"
    create_home: true
    group: users
    groups:
      - wheel
  become: true

- name: Create scripts directory
  ansible.builtin.file:
    name: /home/{{ archlinux_username }}/bin
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0755"
  become: true
  become_user: "{{ archlinux_username }}"

- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ archlinux_username }}/.{{ item }}
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0600"
  with_items:
    - bashrc
    - bash_profile
    - xinitrc
    - direnvrc
  become: true
  become_user: "{{ archlinux_username }}"

- name: Template dotfiles
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /home/{{ archlinux_username }}/.{{ item }}
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0600"
  with_items:
    - Xresources
  become: true
  become_user: "{{ archlinux_username }}"

- name: Create openssh client configuration directory
  ansible.builtin.file:
    dest: /home/{{ archlinux_username }}/.ssh
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0700"
  become: true

- name: Configure openssh client
  ansible.builtin.copy:
    src: openssh/ssh_config
    dest: /home/{{ archlinux_username }}/.ssh/config
    owner: "{{ archlinux_username }}"
    group: users
    mode: "0644"
  become: true
  become_user: "{{ archlinux_username }}"

- name: Install shell colorschemes
  ansible.builtin.git:
    repo: "https://github.com/dharmab/base16-shell.git"
    dest: /home/{{ archlinux_username }}/.config/base16-shell
    version: master
  become: true
  become_user: "{{ archlinux_username }}"
