#!/bin/bash

# Set editor to vim because vi is old and nano is awful
export EDITOR=vim

# Set Java Swing UI Look and Feel to GTK, and nicer font antialiasing
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Determine if a command is available
present() {
    if [ "$#" -ne 1 ]; then
        echo "Usage: present <command>"
    fi

    if type "$1" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

# Set Maven home
if present mvn; then
    export M2_HOME=/opt/maven
fi

# Install and run ruby gems in home directory
if present ruby; then
    GEM_HOME="$(ruby -rubygems -e 'puts Gem.user_dir')"
    export GEM_HOME
    export PATH="$GEM_HOME/bin:$PATH"
fi

# If not running interactively, stop here
[[ $- != *i* ]] && return

# Base16 Shell
# Run `base16_(colorscheme)` to change colors in shell and Vim
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s "$BASE16_SHELL/profile_helper.sh" ] && eval "$("$BASE16_SHELL/profile_helper.sh")"

# Colored output
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# mkdir creates entire directory hierarchy
alias mkdir='mkdir -p'

# Shortcut for organized detailed file list
alias ll='ls -lah --group-directories-first --color=auto'

# Shortcut to go up one directory
alias ..='cd ..'

# Shortcut to get the disk size of a directory and contents
sizeof() {
    if [ "$#" -ne 1 ]; then
        echo "Usage: sizeof <directory>"
        return
    fi
    du -ch "$1" | grep total
    return 0
}

# Set prompt
bash_prompt() {
    # foreground colors
    local COLOR_NONE="\[\033[0m\]"

    # regular colors
    local COLOR_RED="\[\033[0;31m\]"
    local COLOR_BLUE="\[\033[0;34m\]"
    local COLOR_WHITE="\[\033[0;37m\]"

    # USA USA USA
    PS1="${COLOR_RED}[${COLOR_WHITE}\u@\h ${COLOR_BLUE}\W${COLOR_RED}]${COLOR_WHITE}\\$ ${COLOR_NONE}"
}

bash_prompt

# direnv hook
if present direnv; then
    eval "$(direnv hook bash)"
fi
